name: Security Audit & Auto-Patch
permissions:
  contents: write # Required to commit changes
  security-events: write

on:
  schedule:
    - cron: "0 0 * * *" # Daily scan
  push:
    branches: [main]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit-and-patch:
    name: Security Audit & Auto-Patch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "nightly"

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install cargo-audit and cargo-edit
        run: |
          cargo install cargo-audit --locked
          cargo install cargo-edit --locked

      - name: Run initial cargo audit
        id: initial-audit
        run: |
          echo "Running initial security audit..."
          cargo audit --json > audit-report.json || {
            echo "Vulnerabilities detected. Proceeding to patch dependencies."
            echo "has_vulnerabilities=true" >> $GITHUB_OUTPUT
          }

      - name: Patch dependencies
        if: steps.initial-audit.outputs.has_vulnerabilities == 'true'
        run: |
          echo "Parsing audit report for vulnerable packages..."
          # Extract vulnerable crates and update them
          jq -r '.vulnerabilities.packages[] | "cargo add \(.name)@$(echo \(.patched_versions) | jq -r .[0])"' audit-report.json | sh

          echo "Updating Cargo.lock..."
          cargo update

          echo "Re-running audit to verify fixes..."
          cargo audit --json > audit-report-fixed.json || {
            echo "::error::Failed to resolve all vulnerabilities. Manual intervention required."
            exit 1
          }

          echo "All vulnerabilities resolved successfully."

      - name: Commit and push changes
        if: steps.initial-audit.outputs.has_vulnerabilities == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action Bot"
          git add Cargo.toml Cargo.lock audit-report*.json
          git commit -m "Auto-patched security vulnerabilities" || echo "No changes to commit"
          git push origin ${{ github.head_ref || github.ref }}
