name: Security Audit & Auto-Patch
permissions:
  contents: write
  security-events: write

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit-and-patch:
    name: Security Audit & Auto-Patch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-audit and cargo-edit
        run: |
          if ! command -v cargo-audit >/dev/null 2>&1; then
            cargo install cargo-audit --locked
          fi
          if ! command -v cargo-add >/dev/null 2>&1; then
            cargo install cargo-edit --locked
          fi

      - name: Run initial cargo audit
        id: initial-audit
        run: |
          echo "Running initial security audit..."
          if ! cargo audit --json > audit-report.json; then
            echo "Vulnerabilities detected. Proceeding to patch dependencies."
            echo "has_vulnerabilities=true" >> $GITHUB_OUTPUT
          fi

      - name: Patch dependencies
        if: steps.initial-audit.outputs.has_vulnerabilities == 'true'
        run: |
          echo "Parsing audit report for vulnerable packages..."
          jq -r '.vulnerabilities.packages[] | "cargo add \(.name)@$(echo \(.patched_versions) | jq -r .[0])"' audit-report.json | sh
          cargo update
          echo "Re-running audit to verify fixes..."
          if ! cargo audit --json > audit-report-fixed.json; then
            echo "::error::Failed to resolve all vulnerabilities. Manual intervention required."
            exit 1
          fi
          echo "All vulnerabilities resolved successfully."

      - name: Commit and push changes
        if: steps.initial-audit.outputs.has_vulnerabilities == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action Bot"
          git add Cargo.toml Cargo.lock audit-report*.json
          git commit -m "Auto-patched security vulnerabilities" || echo "No changes to commit"
          git push
