# file: changelog.yml
name: Generate Changelog Notes

permissions:
  contents: read

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-changelog-notes:
    name: Generate Release Notes Content
    runs-on: ubuntu-latest
    continue-on-error: false
    outputs:
      changelog_content: ${{ steps.changelog_builder.outputs.changelog }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for tags
        id: check_tags
        run: |
          set -euo pipefail
          if git describe --tags --abbrev=0 > /dev/null 2>&1; then
            echo "tags_exist=true" >> $GITHUB_OUTPUT
            echo "::notice::Tags found."
          else
            echo "tags_exist=false" >> $GITHUB_OUTPUT
            echo "::warning::No tags found. Changelog generation might be empty or fail."

      - name: Generate Changelog Content using Builder Action
        id: changelog_builder
        uses: mikepenz/release-changelog-builder-action@v4
        if: steps.check_tags.outputs.tags_exist == 'true'
        with:
          configuration: ".github/changelog-config.json"
          ignorePreReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Display Generated Changelog
        if: steps.check_tags.outputs.tags_exist == 'true'
        run: |
          echo "Generated Changelog Content:"
          echo "${{ steps.changelog_builder.outputs.changelog }}"
