version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 5
    auto-merge: true
    labels:
      - "dependencies"
      - "github-actions"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
    target-branch: "main"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "rust"
    groups:
      critical-crates:
        patterns:
          - "tokio"
          - "serde"
          - "openssl"
      dev-deps:
        patterns:
          - "clap"
          - "anyhow"
          - "tracing"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
