name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sundays
  workflow_dispatch:

jobs:
  update-deps:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-outdated and cargo-edit
        run: cargo install cargo-outdated cargo-edit

      - name: Check for outdated dependencies
        id: outdated
        run: |
          echo "::group::Checking for outdated dependencies"
          OUTPUT=$(cargo outdated --workspace --exit-code 0)
          echo "$OUTPUT"
          echo "::endgroup::"
          
          echo "outdated<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          body: |
            This PR updates outdated dependencies.
            
            <details>
            <summary>Outdated dependencies</summary>
            
            ```
            ${{ steps.outdated.outputs.outdated }}
            ```
            
            </details>
          branch: update-dependencies
          delete-branch: true