# file: dependencies.yml
name: Update Dependencies

permissions:
  contents: write # Needed to commit dependency updates
  pull-requests: write # Needed to create the pull request

on:
  schedule:
    - cron: "0 3 * * 0" # Run weekly on Sunday at 3 AM UTC
  workflow_dispatch:

# Prevent multiple dependency update runs simultaneously
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-deps:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-outdated
        run: |
          if ! command -v cargo-outdated >/dev/null 2>&1; then
            cargo install cargo-outdated --locked
          fi

      - name: Check for outdated dependencies
        id: outdated
        run: |
          set -euo pipefail
          echo "::group::Checking for outdated dependencies"
          OUTPUT=$(cargo outdated --workspace --exit-code 0 || echo "cargo-outdated failed")
          echo "$OUTPUT"
          echo "::endgroup::"
          echo "outdated_list<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update dependencies using cargo update
        run: cargo update --locked

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore(deps): update Rust dependencies"
          body: |
            Update Rust dependencies based on `cargo update`.

            **Outdated dependencies before update:**
            ```rust
            ${{ steps.outdated.outputs.outdated_list }}
            ```

            *This PR is automatically generated.*
          branch: chore/update-dependencies # Use a more descriptive branch name
          delete-branch: true # Delete branch after merging/closing
          labels: dependencies, automated pr
          assignees: ${{ github.actor }} # Assign the user who triggered it (if manual) or maintainers
